# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets

diretorio_script = os.path.dirname(os.path.abspath(__file__))
logo2_FILE = os.path.join(diretorio_script, 'logo2.png')
logo2_FILE = os.path.join(diretorio_script, 'logo2.png')
icone_canada_FILE = os.path.join(diretorio_script, 'icone_canada.png')
icone_USA_FILE = os.path.join(diretorio_script, 'icone_usa.png')
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(324, 535)
        MainWindow.setStyleSheet("/* style.qss */\n"
"QWidget {\n"
"    background-color: #2E3440;\n"
"    color: #D8DEE9;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4C566A;\n"
"    border: 1px solid #434C5E;\n"
"    color: #D8DEE9;\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #D8DEE9;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #3B4252;\n"
"    border: 1px solid #4C566A;\n"
"    color: #D8DEE9;\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setMaximumSize(QtCore.QSize(228, 155))
                

        self.logoLabel.setPixmap(QtGui.QPixmap(logo2_FILE))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setIndent(32)
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout.addWidget(self.logoLabel, 0, QtCore.Qt.AlignHCenter)
        self.locationLabel = QtWidgets.QLabel(self.centralwidget)
        self.locationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.locationLabel.setObjectName("locationLabel")
        self.verticalLayout.addWidget(self.locationLabel)
        self.completecheckBox = QtWidgets.QCheckBox(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(logo2_FILE), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.completecheckBox.setIcon(icon)
        self.completecheckBox.setObjectName("completecheckBox")
        self.verticalLayout.addWidget(self.completecheckBox)
        self.canadacheckBox = QtWidgets.QCheckBox(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(icone_canada_FILE), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.canadacheckBox.setIcon(icon1)
        self.canadacheckBox.setObjectName("canadacheckBox")
        self.verticalLayout.addWidget(self.canadacheckBox)
        self.usaCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(icone_USA_FILE), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.usaCheckBox.setIcon(icon2)
        self.usaCheckBox.setObjectName("usaCheckBox")
        self.verticalLayout.addWidget(self.usaCheckBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rotationCountLabel = QtWidgets.QLabel(self.centralwidget)
        self.rotationCountLabel.setObjectName("rotationCountLabel")
        self.horizontalLayout.addWidget(self.rotationCountLabel)
        self.rotationCountSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.rotationCountSpinBox.setMinimum(1)
        self.rotationCountSpinBox.setMaximum(100)
        self.rotationCountSpinBox.setObjectName("rotationCountSpinBox")
        self.horizontalLayout.addWidget(self.rotationCountSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.intervalLabel = QtWidgets.QLabel(self.centralwidget)
        self.intervalLabel.setObjectName("intervalLabel")
        self.horizontalLayout_2.addWidget(self.intervalLabel)
        self.intervalSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.intervalSpinBox.setMinimum(1)
        self.intervalSpinBox.setMaximum(3600)
        self.intervalSpinBox.setObjectName("intervalSpinBox")
        self.horizontalLayout_2.addWidget(self.intervalSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.rotateButton = QtWidgets.QPushButton(self.centralwidget)
        self.rotateButton.setObjectName("rotateButton")
        self.verticalLayout.addWidget(self.rotateButton)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout.addWidget(self.stopButton)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.benchmarkButton = QtWidgets.QPushButton(self.centralwidget)
        self.benchmarkButton.setObjectName("benchmarkButton")
        self.verticalLayout.addWidget(self.benchmarkButton)
        self.globalBenchmarkButton = QtWidgets.QPushButton(self.centralwidget)
        self.globalBenchmarkButton.setObjectName("globalBenchmarkButton")
        self.verticalLayout.addWidget(self.globalBenchmarkButton)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nord Vpn Auto Rotate"))
        self.locationLabel.setText(_translate("MainWindow", "N-V-A-R"))
        self.completecheckBox.setText(_translate("MainWindow", "Complete Rotate"))
        self.canadacheckBox.setText(_translate("MainWindow", "Rotate in CANADA"))
        self.usaCheckBox.setText(_translate("MainWindow", "Rotate in USA"))
        self.rotationCountLabel.setText(_translate("MainWindow", "Rotation Count:"))
        self.intervalLabel.setText(_translate("MainWindow", "Interval (seconds):"))
        self.rotateButton.setText(_translate("MainWindow", "Rotate VPN"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.benchmarkButton.setText(_translate("MainWindow", "View Benchmark"))
        self.globalBenchmarkButton.setText(_translate("MainWindow", "View Global Benchmark"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "                       YOU HERE N-V-A-R SERIAL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
